services:
  build:
    build: .
    user: builder
    environment:
      - PATH=/home/builder/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
      - .:/home/builder/app
    command: >
      bash -c "sudo chown -R builder:builder /home/builder/app && cd /home/builder/app && buildozer android debug"
